### ISSUE TITLE
Presets for popular Seamark tags

### ISSUE THREAD

**Issue by k-yle** [openstreetmap/id-tagging-schema#683]
This issue tracks the progress of creating presets for popular [Seamark tags](https://wiki.osm.org/Seamarks/Seamark_Objects).

Numbers indicate tag usage as of December 2022.

## Buoys and Beacons

Currently being discussed in #512

- Buoys
  - [ ] [Cardinal Buoy](https://wiki.osm.org/Tag:seamark:type=buoy_cardinal) `10k`
  - [ ] [Isolated Danger Buoy](https://wiki.osm.org/Tag:seamark:type=buoy_isolated_danger) `600`
  - [x] [Lateral Buoy](https://wiki.osm.org/Tag:seamark:type=buoy_lateral) (a.k.a. Channel Buoy) `56k` [iD#5297](https://github.com/openstreetmap/iD/pull/5297)
  - [ ] [Safe Water Buoy](https://wiki.osm.org/Tag:seamark:type=buoy_safe_water) `1k`
  - [ ] [Special Purpose Buoy](https://wiki.osm.org/Tag:seamark:type=buoy_special_purpose) (a.k.a. Generic Buoy) `12k`
  - [x] Mooring - see below
  - [ ] Visitor Mooring - see below
- Beacons
  - [ ] [Cardinal Mark](https://wiki.osm.org/Tag:seamark:type=beacon_cardinal) `1k`
  - [x] [Isolated Danger Mark](https://wiki.osm.org/Tag:seamark:type=beacon_isolated_danger) `14k` [iD#5297](https://github.com/openstreetmap/iD/pull/5297)
  - [x] [Lateral Mark](https://wiki.osm.org/Tag:seamark:type=beacon_lateral) (a.k.a. Channel Beacon) `27k` [iD#5297](https://github.com/openstreetmap/iD/pull/5297)
  - [ ] ~~[Safe Water Mark](https://wiki.osm.org/Tag:seamark:type=beacon_safe_water) `98`~~[^1]
  - [ ] [Special Purpose Mark](https://wiki.osm.org/Tag:seamark:type=beacon_special_purpose) (a.k.a. Generic Mark) `14k`

## Other feasible presets

- [x] [Piers/Jettys/Pontoons](https://wiki.osm.org/Tag:man_made=pier) `572k`
- [x] [Mooring](https://wiki.osm.org/Tag:seamark:type=mooring) `58k` [iD#5297](https://github.com/openstreetmap/iD/pull/5297)
- [x] [Slipway](https://wiki.osm.org/Tag:leisure=slipway) `49k`
- [x] [Ferry routes](https://wiki.osm.org/Tag:route=ferry) `29k` [iD#5416](https://github.com/openstreetmap/iD/pull/5416)
- [x] [Ferry terminal](https://wiki.osm.org/Tag:amenity=ferry_terminal) `29k` [iD#2883](https://github.com/openstreetmap/iD/issues/2883)
- [x] [Marina](https://wiki.osm.org/Tag:leisure=marina) `27k`
- [x] [Lock Gate](https://wiki.osm.org/Tag:waterway=lock_gate) `22k`
- [ ] [Navigation Line](https://wiki.osm.org/Tag:seamark:type=navigation_line) & [Recommended Track](https://wiki.osm.org/Tag:seamark:type=recommended_track) `20k` + `3k`
- [ ] [Pile](https://wiki.osm.org/Tag:seamark:type=pile) `19k`
- [ ] [Distance Mark](https://wiki.osm.org/Tag:seamark:type=distance_mark) `13k`
- [ ] [Bridge height/width restriction](https://wiki.osm.org/Tag:seamark:type=bridge) `10k`
- [x] [Wreck](https://wiki.osm.org/Tag:historic=wreck) `5k` [iD#5302](https://github.com/openstreetmap/iD/pull/5302)
- [ ] [Berth](https://wiki.osm.org/Tag:seamark:type=berth) & [Anchor Berth](https://wiki.osm.org/Tag:seamark:type=anchor_berth) `4k` + `0.6k`
- [ ] [Anchorage Area](https://wiki.osm.org/Tag:seamark:type=anchorage) `4k`
- [ ] [Restricted Area](https://wiki.osm.org/Tag:seamark:type=restricted_area) `3k`
- [ ] [Offshore Platform](https://wiki.osm.org/Tag:seamark:type=platform) `3k`
- [ ] [Fairway](https://wiki.osm.org/Tag:seamark:type=fairway) `1.6k`
- [x] [Lifeboat Station](https://wiki.osm.org/Tag:seamark:type=rescue_station) `600` [#76](https://github.com/openstreetmap/id-tagging-schema/issues/76)
- [ ] [VHF calling-in point](https://wiki.osm.org/Tag:seamark:type=calling-in_point) `400`
- [ ] [Pilot boarding point](https://wiki.osm.org/Tag:seamark:type=pilot_boarding) `500`
- [ ] [Virtual Aid to Navigation (AtoN)](https://wiki.osm.org/Tag:seamark:type=virtual_aton) `300`
- [ ] [Seaplane Landing Area](https://wiki.osm.org/Tag:seamark:type=seaplane_landing_area) `100` - [#569](https://github.com/openstreetmap/id-tagging-schema/issues/569)
- "Small Craft Facilities"
  - [x] [Marine Fuel](https://wiki.osm.org/Tag:seamark:small_craft_facility:category=fuel_station) `600` [iD#2589](https://github.com/openstreetmap/iD/issues/2589)
  - [x] [Marine Toilet Disposal](https://wiki.osm.org/Tag:seamark:small_craft_facility:category=pump-out) `500` [iD#2623](https://github.com/openstreetmap/iD/issues/2623)
  - [ ] [Visitor Berth](https://wiki.osm.org/Tag:seamark:small_craft_facility:category=visitor_berth) `900`
  - [ ] [Visitor Mooring](https://wiki.osm.org/Tag:seamark:small_craft_facility:category=visitors_mooring) `76` too rare?

## Obscure features

Probaby not appropriate to create presets for these

- [ ] [Marine Dumping Ground](https://wiki.osm.org/Tag:seamark:type=dumping_ground) `200`
- [ ] [Hulk](https://wiki.osm.org/Tag:seamark:type=hulk) `200`
- [ ] Traffic Separation Schemes ([lane](https://wiki.osm.org/Tag:seamark:type=separation_lane), [line](https://wiki.osm.org/Tag:seamark:type=separation_line), [zone](https://wiki.osm.org/Tag:seamark:type=separation_zone), [roundabout](https://wiki.osm.org/Tag:seamark:type=separation_roundabout), [crossing](https://wiki.osm.org/Tag:seamark:type=separation_crossing), [boundary](https://wiki.osm.org/Tag:seamark:type=separation_boundary), [inshore](https://wiki.osm.org/Tag:seamark:type=inshore_traffic_zone)) `800`
  - usually miles away from the shore, and will never need to be editted

## Too complex

It may be too complicated to add some of these features due to their tagging system:

- [ ] [Simple Lights](https://wiki.osm.org/Seamarks/Lights) [`50k`](https://taginfo.osm.org/keys/seamark:light:colour)
- [ ] [Sectored Lights](https://wiki.osm.org/Seamarks/Lights) [`11k`](https://taginfo.osm.org/keys/seamark:light:1:colour)
- [ ] [Notice Marks](https://wiki.osm.org/Seamarks/Notice_Marks) `23k`
  - Regional presets are supported so this could be possible for just Europe
- [ ] [Marine Rock](https://wiki.osm.org/Tag:seamark:type=rock) `120k` and [Marine Obstruction](https://wiki.osm.org/Tag:seamark:type=obstruction) `5k`
  - May be confusing since these two are similar, and there are already presets for `Rock`, `Boulder`, and `Bare Rock`
- [ ] [Fog Signal](https://wiki.osm.org/Seamarks/Fog_Signals) `1k`
  - nearly always combined with another feature, so this would just be fields.
- [ ] [Signal Station](https://wiki.osm.org/Seamarks/Signal_Stations) `1.6k` + `1.3k`
  - two different top-level tags ('[traffic](https://wiki.osm.org/Tag:seamark:type=signal_station_traffic)' vs '[warning](https://wiki.osm.org/Tag:seamark:type=signal_station_warning)'), might be confusing what the differece is. Ideally this would be one preset.

## Things to consider

- 7 different presets for buoys and 4 for beacons will be very confusing. Ideally it would be 1 preset for buoys, but this isn't possible since they all have different top-level tags.
- Would 21 new presets overwhelm mappers? Should they be hidden except unless you turn a special mode?
- OpenSeaMap background imagery https://github.com/openstreetmap/iD/pull/8824

[^1]: Much less common than the others because the water (usually) can't be _safe_ if it's shallow enough for a beacon

**Comment by matkoniecz** [comment]
`seamark:type=fairway` seems to duplicate `waterway=fairway` without a good reason, see https://wiki.openstreetmap.org/wiki/Tag:seamark:type%3Dfairway and https://wiki.openstreetmap.org/wiki/Tag:waterway%3Dfairway

**Comment by k-yle** [comment]
`seamark:type=fairway` is for the area, `waterway=fairway` is for the linear centreline. 

The tags have two totally separate purposes, but the wiki doesn't explain it well. 

- `waterway=fairway` (line) is used by routers along with `waterway=stream/canal/river`. It exists purely for routing.
- `seamark:type=fairway` (area) denotes the geographical limit of the fairway & its assosiated restrictions (like `no_anchoring`, `no_fishing` etc.)

**Comment by jsavage** [comment]
> `seamark:type=fairway` seems to duplicate `waterway=fairway` without a good reason, see https://wiki.openstreetmap.org/wiki/Tag:seamark:type%3Dfairway and https://wiki.openstreetmap.org/wiki/Tag:waterway%3Dfairway

As a skipper of a yacht, it seems rather pointless to mark a fairway on a chart or OSM.  We talk loosely about 'fairways' but I am not convinced that the term is that useful or that there is any useful purpose in marking them - after all, they are usually defined (Bordered) by other navigation aids such as buoyage and in some cases geography.
Unless someone can come up with a use case my recommendation would be to consider dropping both definitions.
